### ISSUE TITLE
Compatibility with Draft JS

### ISSUE THREAD

**Issue by tyherox** [mulesoft/md-draft-js#4]
Hey @nescalante thanks for the wonderful library.

I have need of switching back and forth from markdown mode and rich text (draft.js) mode and was wondering about the compatibility between the two libraries.

**Comment by DaniGuardiola** [comment]
I also wanna know about this :)

**Comment by gnbonney** [comment]
There are other projects out there that deal with converting Draft.js to markdown and back. Try markdown-draft-js or react-rte for example.

**Comment by tyherox** [comment]
As mentioned by @gnbonney, I ended up using my own draft-js implementation and [markdown-draft-js](https://github.com/Rosey/markdown-draft-js#readme) for my project. It has minor hiccups here and there but works well enough for us. Recommended!
